# CS50's Introduction to Programming with Python (CS50P) 2022 
# https://cs50.harvard.edu/python/2022/weeks/6/
# https://www.youtube.com/playlist?list=PLhQjrBD2T3817j24-GogXmWqO5Q5vYy0V
# https://youtu.be/KD-Yoel6EVQ

# https://cs50.harvard.edu/python/2022/notes/6/

"""
Lecture 6

    File I/O
    open
    with
    CSV
    Binary Files and PIL
    Summing Up

File I/O

- Up until now, everything we’ve programmed has stored information in memory. That is, once the program is ended, all information gathered from the user or generated by the program is lost.
- File I/O is the ability of a program to take a file as input or create a file as output.
- To begin, in the terminal window type code names.py and code as follows:
"""
name = input("What's your name?" )
print(f"hello, {name}")
"""
- Notice that running this code has the desired output. The user can input a name. The output is as expected.
- However, what if we wanted to allow multiple names to be inputted? How might we achieve this? Recall that a list is a data structure that allows us to store multiple values into a single variable. Code as follows:
"""
names = []

for _ in range(3):
    name = input("What's your name?" )
    names.append(name)
"""
- Notice that the user will be prompted three times for input. The append method is used to add the name to our names list.
- This code could be simplified to the following:
"""
names = []

for _ in range(3):
    names.append(input("What's your name?" ))
"""
- Notice that this has the same result as the prior block of code.
- Now, let’s enable the ability to print the list of names as a sorted list. Code as follows:
"""
names = []

for _ in range(3):
    names.append(input("What's your name?" ))

for name in sorted(names):
    print(f"hello, {name}")
"""
- Notice that once this program is executed, all information is lost. File I/O allows your program to store this information such that it can be used later.
- You can learn more in Python’s documentation of sorted.
"""
